[package]
name = "max_finder"
version = "0.1.0"
edition = "2018"

[dependencies]
ndarray = "0.15"
sys-info = "0.9"
csv = "1.1"
statrs = "0.14"

[dev-dependencies]
pretty_assertions = "0.7"

[lib]
name = "max_finder"
path = "src/lib.rs"
